name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_DB: factori_test
          POSTGRES_PASSWORD: boilerplate
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      MIX_ENV: test
      DATABASE_URL: postgres://postgres:boilerplate@localhost/factori_test
      DATABASE_POOL_SIZE: 30

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles(format('{0}/mix.lock', github.workspace)) }}

      - run: make prepare
      - run: make check-format
      - run: make check-unused-dependencies
      - run: make lint
      - run: make dialyzer
      - run: make test
